---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: mixed-line-ending
      - id: requirements-txt-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.0
    hooks:
      - id: yamllint
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.46.0
    hooks:
      - id: cfn-python-lint
        files: "template.(yml|yaml)"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/awslabs/git-secrets
    rev: master
    hooks:
      - id: git-secrets
