---
name: it

on:
  pull_request:
    branches:
      - main

jobs:
  it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Validate with sam validate
        uses: youyo/aws-sam-action@v2.0.1
        with:
          sam_command: validate
          actions_comment: true
      - name: Build application with sam build
        uses: youyo/aws-sam-action@v2.0.1
        with:
          sam_command: build --use-container
      - name: Generate uuid
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
      - name: Deploy application with sam deploy
        uses: youyo/aws-sam-action@v2.0.1
        with:
          sam_command: deploy --stack-name \
              ${{ github.repository }}-${{ steps.generate_uuid.outputs.uuid }}\
            --no-confirm-changeset\
            --parameter-overrides HookUrl=${{ secrets.HOOK_URL }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Destroy stack
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: cloudformation delete-stack\
            --stack-name\
            ${{ github.repository }}-${{ steps.generate_uuid.outputs.uuid }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
