---
name: ut

on: push

jobs:
  ut:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r tests/requirements.txt
          python -m pip install -r \
            aws_codecommit_notification_4_teams/requirements.txt
      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics
      - name: Lint with yamllint
        run: yamllint -f github .
      - name: Lint with cfn-lint
        run: cfn-lint -I template.yaml
      - name: Test with pytest (unit)
        run: py.test tests/unit
